### ISSUE TITLE
Error: cannot find module 'next'

### ISSUE THREAD

**Issue by offeca** [decolua/9router#1101]
After updating to v0.4.38
Input in cmd 9router --> error message shows up:


⚠️  Server exited (code=1). Restarting in 1s... (1/2)                                                                                                                                                                                         --- Server crash log ---                                                                                                node:internal/modules/cjs/loader:1386                                                                                     throw err;                                                                                                              ^                                                                                                                                                                                                                                             Error: Cannot find module 'next'                                                                                        Require stack:                                                                                                          - C:\Users\Admin\AppData\Roaming\npm\node_modules\9router\app\server.js                                                     at Function._resolveFilename (node:internal/modules/cjs/loader:1383:15)                                                 at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)                                                        at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)                                                    at Function._load (node:internal/modules/cjs/loader:1192:37)                                                            at TracingChannel.traceSync (node:diagnostics_channel:328:14)                                                           at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)                                                             at Module.require (node:internal/modules/cjs/loader:1463:12)                                                            at require (node:internal/modules/helpers:147:16)                                                                       at Object.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\9router\app\server.js:16:1)                      at Module._compile (node:internal/modules/cjs/loader:1705:14) {                                                       code: 'MODULE_NOT_FOUND',                                                                                               requireStack: [                                                                                                           'C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\9router\\app\\server.js'                                      ]                                                                                                                     }                                                                                                                                                                                                                                               Node.js v22.22.2                                                                                                        --- End crash log ---     

No docker, just installed on windows 
OS: Windows 10 22H2

v0.4.37 worked fine. 
How to revoke to previous version?

**Comment by indrapalijama** [comment]
maybe use `npm i 9router@0.4.37`? but i still got the same error

**Comment by samuelricko** [comment]
`npm i 9router@0.4.36`

to rollback

**Comment by indrapalijama** [comment]
> `npm i 9router@0.4.36`
> 
> to rollback

still got error, the process automatically killed. Urgh

**Comment by trustmebaby789-boop** [comment]
same issues

**Comment by trustmebaby789-boop** [comment]
> > `npm i 9router@0.4.36`
> > to rollback
> 
> still got error, the process automatically killed. Urgh

npm i -g next
9router  " ok with this

**Comment by trustmebaby789-boop** [comment]
npm i -g next
9router


i tried with this its okay now

**Comment by indrapalijama** [comment]
> npm i -g next 9router
> 
> i tried with this its okay now

latest version? or downgraded one?

**Comment by trustmebaby789-boop** [comment]
on Linux Ubuntu
> > npm i -g next 9router
> > i tried with this its okay now
> 
> latest version? or downgraded one?

lastest one 

<img width="637" height="354" alt="Image" src="https://github.com/user-attachments/assets/7cd0e943-5bf5-429f-9d08-44af71fcb369" />

>

**Comment by offeca** [comment]
rolledback using the following command:

uninstall
'npm uninstall -g 9router'

then reinstall
'npm install -g 9router@0.4.36'

**Comment by indrapalijama** [comment]
> > > npm i -g next 9router
> > > i tried with this its okay now
> > 
> > 
> > latest version? or downgraded one?
> 
> lastest one
> 
> <img alt="Image" width="637" height="354" src="https://private-user-images.githubusercontent.com/278606440/591941554-7cd0e943-5bf5-429f-9d08-44af71fcb369.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Nzg2OTEyNDcsIm5iZiI6MTc3ODY5MDk0NywicGF0aCI6Ii8yNzg2MDY0NDAvNTkxOTQxNTU0LTdjZDBlOTQzLTViZjUtNDI5Zi05ZDA4LTQ0YWY3MWZjYjM2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDUxM1QxNjQ5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDY1OTNkY2ZjMDhkZDFjZmVkYjc2ZmMwMzk2YmU0ZDdhOWVlYmQwM2EwZjMwODc0ZDZmOGUyMGI5NWRlZDM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.3ybGQjPN6aojKmt3ZcudwdKJJO4IwF8ilwLhq7bOxew">
> >

is it a linux? strangely, it doesn't work in my m1

**Comment by trustmebaby789-boop** [comment]
> > > > npm i -g next 9router
> > > > i tried with this its okay now
> > > 
> > > 
> > > latest version? or downgraded one?
> > 
> > 
> > lastest one
> > <img alt="Image" width="637" height="354" src="https://private-user-images.githubusercontent.com/278606440/591941554-7cd0e943-5bf5-429f-9d08-44af71fcb369.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Nzg2OTEyNDcsIm5iZiI6MTc3ODY5MDk0NywicGF0aCI6Ii8yNzg2MDY0NDAvNTkxOTQxNTU0LTdjZDBlOTQzLTViZjUtNDI5Zi05ZDA4LTQ0YWY3MWZjYjM2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDUxM1QxNjQ5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDY1OTNkY2ZjMDhkZDFjZmVkYjc2ZmMwMzk2YmU0ZDdhOWVlYmQwM2EwZjMwODc0ZDZmOGUyMGI5NWRlZDM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.3ybGQjPN6aojKmt3ZcudwdKJJO4IwF8ilwLhq7bOxew">
> > >
> 
> is it a linux? strangely, it doesn't work in my m1

yess linux

**Comment by indrapalijama** [comment]
sigh, i'm fixing it by using docker version

**Comment by ridwanramadhan** [comment]
Fixed in v0.4.39, which is already `latest` on npm.

Quick context on what broke: v0.4.38 had the CLI build set `outputFileTracingRoot` to the project root, so Next.js' standalone trace missed the hoisted `next` package. The npm tarball shipped `app/server.js` without `node_modules/next` next to it, and `require('next')` blew up at startup on non-Docker installs.

Commit `a8100e9` switches the CLI to a workspace-rooted trace (`NEXT_TRACING_ROOT_MODE=workspace`) and bundles the traced `node_modules/` alongside `app/`.

Reinstall:

```bash
npm uninstall -g 9router
npm install -g 9router@latest
9router --version   # 0.4.39
```

**Comment by indrapalijama** [comment]
> Fixed in v0.4.39, which is already `latest` on npm.
> 
> Quick context on what broke: v0.4.38 had the CLI build set `outputFileTracingRoot` to the project root, so Next.js' standalone trace missed the hoisted `next` package. The npm tarball shipped `app/server.js` without `node_modules/next` next to it, and `require('next')` blew up at startup on non-Docker installs.
> 
> Commit `a8100e9` switches the CLI to a workspace-rooted trace (`NEXT_TRACING_ROOT_MODE=workspace`) and bundles the traced `node_modules/` alongside `app/`.
> 
> Reinstall:
> 
> npm uninstall -g 9router
> npm install -g 9router@latest
> 9router --version   # 0.4.39

Thanks, for now. 0.4.39 is probably our best bet, because latest version is broken again, also why 9router keeps persist on installing better sqlite in runtime? even tho we're manually installing it using the said command.
`[9router][runtime] npm install better-sqlite3@12.6.2 --no-audit --no-fund --prefer-online --no-save`

**Comment by claytontavaresdan** [comment]
## Solution for 'cannot find module next' Error

### Quick Fix
```bash
# Clean reinstall
rm -rf node_modules
npm install
npm run build
npm run start
```

### Alternative Solutions

1. **Clear npm cache**
```bash
npm cache clean --force
rm -rf node_modules
npm install
```

2. **Check Node.js version**
```bash
node --version  # Should be 18+
nvm install 22
nvm use 22
```

3. **Verify package.json**
```bash
cat package.json | grep next
# If missing: npm install next@latest
```

### Prevention
- Always run `npm install` after updating
- Use Node.js 18+ LTS version
- Consider using Docker for consistent environment

This should resolve the module not found error!
