### ISSUE TITLE
Error: Cannot find module '/app/server.js'

### ISSUE THREAD

**Issue by cencencendi** [decolua/9router#1055]
Hi, I hit a Docker runtime failure on Linux after updating to v0.4.31/v0.4.33.
Error: Cannot find module '/app/server.js'

The current Dockerfile copies:
COPY --from=builder /app/.next/standalone ./

But in my build, the actual Next standalone output is:
/app/.next/standalone/app/server.js

So the image ends up with:
/app/app/server.js

while the container starts with:
CMD ["node", "server. js"]
Changing the Dockerfile to:
COPY --from=builder /app/.next/standalone/app ./
fixed it for me.

I verified the issue is still present in tag v0.4.33.

**Comment by rubby1228** [comment]
Already reported here #1039
