### ISSUE TITLE
Error: 'NoneType' object has no attribute 'type'

### ISSUE THREAD

**Issue by dungnguyenv90** [decolua/9router#596]
After update to new version to 0.3.91, the Hermes agent got an error: **Error: 'NoneType' object has no attribute 'type'**
Sent test on Provider (Web UI), the models are still working.

```
API call failed (attempt 1/3): AttributeError
   🔌 Provider: custom  Model: cx/gpt-5.4
   🌐 Endpoint: http://localhost:20128/v1
   📝 Error: 'NoneType' object has no attribute 'type'
⏳ Retrying in 2.4301481515372294s (attempt 1/3)
```

**Comment by dungnguyenv90** [comment]
Maybe the reason is from Hermes agent.
