### ISSUE TITLE
Docker image broken again in v0.4.36 / v0.4.37: /app/server.js missing (regression of #1064)

### ISSUE THREAD

**Issue by ridwanramadhan** [decolua/9router#1096]
## Summary

`v0.4.36` and `v0.4.37` re-introduce the same `MODULE_NOT_FOUND: '/app/server.js'` failure that was reported in #1064 and fixed by #1067. The fix was reverted in the `v0.4.36` release commit (`7ccf8c5`) under a different variable name (`monorepoRoot` → `workspaceRoot`), with the same broken behaviour.

## Affected Versions

| Version | Status |
|---------|--------|
| `v0.4.37` (`:latest`) | ❌ Broken |
| `v0.4.36` | ❌ Broken |
| `v0.4.33` | ❌ Broken (original #1064) |
| `v0.4.31` | ❌ Broken (original #1064) |
| `v0.4.30` | ✅ Works |

> Note: `v0.4.32`, `v0.4.34`, `v0.4.35` were never published, so even though #1067 was merged before `v0.4.36`, no released image ever shipped with the fix.

## Environment

- Image: `ghcr.io/decolua/9router:0.4.37` (and `:latest`, and `decolua/9router:0.4.37` on Docker Hub)
- Platform: `linux/amd64`
- Host OS: Ubuntu 22.04
- Docker: 27.x with Docker Compose v2

## Reproduction

```bash
docker pull ghcr.io/decolua/9router:0.4.37
docker run --rm ghcr.io/decolua/9router:0.4.37
```

## Error Output

```
Error: Cannot find module '/app/server.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1383:15)
    ...
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Node.js v22.22.2
```

Container enters a restart loop. Inspecting `/app` shows `server.js` at `/app/app/server.js` (nested) along with stray `proc`, `root`, `usr` directories — identical to the layout described in #1064.

## Root Cause

In commit `7ccf8c5` (the `v0.4.36` release), `next.config.mjs` was changed:

```diff
-const projectRoot = dirname(fileURLToPath(import.meta.url));
+const projectRoot = dirname(fileURLToPath(import.meta.url));
+// Workspace root (one level up from app/) — where npm hoists deps.
+// Next.js tracing must scan from here to find "next", "react", etc.
+const workspaceRoot = join(projectRoot, "..");
 ...
-  outputFileTracingRoot: projectRoot,
+  outputFileTracingRoot: workspaceRoot,
```

This is functionally identical to the original `monorepoRoot` regression fixed in #1067. Inside the Docker builder, `join("/app", "..")` resolves to `/`, so Next.js writes the standalone output preserving absolute paths — `server.js` lands at `.next/standalone/app/server.js`, and traced files from `/usr`, `/root`, `/proc` get mirrored alongside. After `COPY --from=builder /app/.next/standalone ./` in the runner stage, the image ends up with `/app/app/server.js` (nested) instead of `/app/server.js`, so `CMD ["node", "server.js"]` fails.

## Why the Revert Likely Happened

The `v0.4.36` changelog mentions:

> Fix Docker `Cannot find module 'next'` error in standalone build

#1067 merged but no image was published between that merge and the `v0.4.36` release commit, so the maintainer likely hit `Cannot find module 'next'` while preparing the `v0.4.36` build locally and reverted the tracing-root change to get past it. Unfortunately the revert restores #1064 instead of solving both problems together.

## Proposed Fix

Keep `outputFileTracingRoot: projectRoot` (so `server.js` lands at `/app/server.js`) **and** ensure `next` is present in the runner image — following the same pattern already used for `node-forge` in the current Dockerfile.

`next.config.mjs`:

```js
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";

const projectRoot = dirname(fileURLToPath(import.meta.url));

const nextConfig = {
  output: "standalone",
  serverExternalPackages: ["better-sqlite3", "sql.js", "node:sqlite", "bun:sqlite"],
  turbopack: { root: projectRoot },
  outputFileTracingRoot: projectRoot,
  outputFileTracingExcludes: {
    "*": ["./gitbook/**/*"]
  },
  // ...
};
```

`Dockerfile` (runner stage) — add a line next to the existing `node-forge` copy:

```dockerfile
COPY --from=builder /app/.next/standalone ./
# ...existing copies...
COPY --from=builder /app/node_modules/node-forge ./node_modules/node-forge
# New: ensure `next` is available at runtime if tracing did not include it.
COPY --from=builder /app/node_modules/next ./node_modules/next
```

This is portable (no hard-coded `WORKDIR` basename in the COPY path) and addresses both failure modes in one change.

## Verification

After applying the fix locally:

```bash
docker build -t 9router-fix .
docker run --rm --entrypoint sh 9router-fix -c "ls -la /app/server.js"
# -> -rw-r--r-- 1 node node 7203 May 13 02:23 /app/server.js

docker run --rm 9router-fix
# -> server starts on port 20128, no MODULE_NOT_FOUND
```

## Workaround

Pin to `v0.4.30`, the last published image that boots correctly:

```yaml
services:
  9router:
    image: ghcr.io/decolua/9router:0.4.30
```

## References

- Original report: #1064
- Original fix: #1067 (commit `692d1fd`)
- Reverted in: commit `7ccf8c5` (`v0.4.36` release)

Happy to send the PR.

**Comment by njzc** [comment]
still not working in 0.4.38 

Container started
node:internal/modules/cjs/loader:1386
  throw err;
  ^
Error: Cannot find module '/app/server.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1383:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
    at Function._load (node:internal/modules/cjs/loader:1192:37)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Node.js v22.22.2
Container stopped

**Comment by ridwanramadhan** [comment]
@njzc the fix actually landed in v0.4.39, not v0.4.38. The changelog credits #1097 under v0.4.38 but the image that actually contains the fix is v0.4.39. I'm running it via `:latest` now and it boots clean.

Try either `:latest` or pin to v0.4.39:

```yaml
# either one works
image: ghcr.io/decolua/9router:latest
# or
image: ghcr.io/decolua/9router:0.4.39
```

If you already pulled it before and it's still failing, do a clean pull — Docker caches by tag:

```bash
docker rmi ghcr.io/decolua/9router:latest
docker compose pull && docker compose up -d
```

**Comment by njzc** [comment]
Hi @ridwanramadhan.  It works in v0.4.39!
Thank you for fixing it!
